postgres:  
  image: postgres:9.5
  
microblog:  
  build: .
  dockerfile: Dockerfile-dev
  ports:
    - "5555:5000"
    - "2000:22"
  volumes:
    - ../src:/app/src/
    - .pycharm_helpers/:/root/.pycharm_helpers
  links:
    - postgres


