postgres:  
  image: radekj/microblog-pg:latest
  
microblog:  
  image: radekj/microblog:latest
  ports:
    - "5000:5000"
    - "2000:22"
  volumes:
    - ../src:/app/src/
    - .pycharm_helpers/:/root/.pycharm_helpers
  links:
    - postgres


